### ISSUE TITLE
The async backedn processing is done in a clean way, with a "job number" and tracking and logging so that if something goes wrong, it is easy to debug.

### ISSUE THREAD

**Issue by pconrad** [brownfield-team/demo-spring-react-example-v2#11]
- [ ] Any time a background job is created, an entry is made in a "jobs" table and the job is assigned  an "id" (just the name id available in that table)
- [ ] There is a menu option available to admins to see the status of jobs
- [ ] Any job in the table is initially shown as "in progress" along with it's start time.
- [ ] Within a "job" it is possible to inquire about the job's "id" and update a job's "summary" or "status message".
- [ ] Within a "job" if there is an uncaught exception thrown, a quick summary of the exception is put in the status message, and the full stack trace is stored in another field.  (that field might not be shown on the page, but is available in the SQL view of the databse, or through swagger, or might be added to the ui later.)
- [ ] Within a "job" when the job completes, there is some default completion message, that can be overridden with a custom completion message (perhaps with a summary of counts of how many things were done, as a sanity check.)

# Notes

* We should try to make sure we have a single clean UI for jobs
* If two different users are running the same job at the same time with the same destination repo, that's not ideal; it would be nice if there were some way to prevent that; e.g. before you start a job, you check if there is already an instance of that job running that has the same "key values" (whatever those might be, e.g. the name of a destination repo), and it either refuses to run the second instance, or it queues it for later (probably refusing is easier).   That would require, probably, some way for an "admin" to "cancel" a "stuck job", e.g. if a job is in an infinite loop (or if it crashed in a way that makes it appear that it's still running even when it is not), so that the next version of that can be run.
